import multer from "multer";

export function errorHandler(err, req, res, next) {
  // Log actual error on server
  console.error(err);

  // Handle file upload errors generated by Multer
  if (err instanceof multer.MulterError) {
    if (err.code === "LIMIT_FILE_SIZE") {
      return res.status(413).json({
        detail: "Uploaded file is too large.",
      });
    }

    return res.status(400).json({
      detail: "Invalid file upload.",
    });
  }

  // Determine HTTP status code
  const status = err.response?.status || err.status || 500;

  // Get message from known errors
  const originalMessage =
    err.response?.data?.detail ||
    err.message ||
    "Something went wrong";

  // Hide internal details for server errors
  const detail =
    status >= 500
      ? "Internal server error"
      : originalMessage;

  return res.status(status).json({ detail });
}